linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  enable:
    - dupl
    - errcheck
    - forcetypeassert
    - gofmt
    - goimports
    - gomodguard
    - gosimple
    - govet
    # - ireturn
    - lll
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - predeclared
    - stylecheck
    - typecheck
    - unparam
    - unused
  # # Enable presets.
  # # https://golangci-lint.run/usage/linters
  # presets:
  #   - bugs
  #   - comment
  #   - complexity
  #   - error
  #   - format
  #   - import
  #   - metalinter
  #   - module
  #   - performance
  #   - sql
  #   - style
  #   - test
  #   - unused
  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: true
  issues:
  # new-from-rev: origin/dev # report only new issues with reference to dev branch
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl